# Site settings
title: Muhamad Ridwan
description: 'Java Programmer yang berfokus di back end, tapi tidak keberatan juga kalo diminta mengerjakan project front end. :)'
url: 'https://muhamadridwan.id'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'muhamadridwan'

author:
  name: 'Muhamad Ridwan'
  email: me@muhamadridwan.id
  facebook_username: m0ridwan
  github_username:  muhamadridwanid
  linkedin_username:  muhamad-ridwan-b3b560124

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
